# Generated by Django 3.2 on 2021-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contact Details',
            },
        ),
    ]
