# Generated by Django 3.2 on 2021-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
