# Generated by Django 3.2 on 2021-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactdetails_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='email',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
